### ISSUE TITLE
Executable is gone

### ISSUE THREAD

**Issue by wdburgdorf** [breca/elite_bgs_companion#29]
I was looking for the recent version, now the executable and oter files seem to be missing. What's happening?

**Comment by jimcheetham** [comment]
Looks like a production issue - the webserver has failed to renew its TLS certificate, and has also failed to log this failure :-|
I'll update here when its fixed.

**Comment by jimcheetham** [comment]
The server is now running properly, and I'll fix up the certbot issues in the background. Can you confirm that you can get the files you wanted now?

**Comment by wdburgdorf** [comment]
Thanks for the fix. But now: 404 Not Found

**Comment by jimcheetham** [comment]
Interesting issue; a mistake in the server config file allowed an unexpected URL pattern to succeed ... this pattern was baked into the distributed executable ... the TLS certificate failed to update correctly (because of an issue with a different certificate that failed renewal, sadly) ... when I fixed that the web server restarted with the "correct" configuration.

So now I've allowed the old 'unexpected' URL to match, explicitly. Thanks for your patience :-)

**Comment by breca** [comment]
Looking good now, thanks @jimcheetham
